### PR TITLE
Installation Requirements, Project Clean Up, Local W2V File Removal

### PR DESCRIPTION
**Pull request by YolandaMDavis**
@Reem2411  and @nlp-nathan . This PR represents the final steps for the project and will require testing to ensure that brand new users will be able to perform the steps.  In this PR I have removed ALL of the locally downloaded w2v files and ensured they will be ignored from git. This will ensure we can recreate experience of the user upon initial setup.

Using this branch and a NEW Python Virtual Environment please follow the steps in the README file to install required libraries, download required files (with correct name and location) and ensure all notebooks execute as expected. It is very important to do this from a scratch environment and not to use any virtual env that you may have been using.  Uploading to colab can also be useful as long as the libraries required can be installed (some may not be available by default on colab).

Please use this PR and slack to alert of any issues or questions.

### CODE REVIEW

**Comment by nlp-nathan** [comment]
- Could you delete all the .txt files in data/analogies folder. Don't delete the folder EN-GOOGLE and its single file

Ran everything in a new environment. It all works.

**Review by nlp-nathan — APPROVED** [review]
It works using a new virtual env

**Comment by YolandaMDavis** [comment]
> * Could you delete all the .txt files in data/analogies folder. Don't delete the folder EN-GOOGLE and its single file
> 
> Ran everything in a new environment. It all works.

Yes I wasn't sure if those files need to be there. I can remove them an add them to .gitignore.

**Comment by Reem2411** [comment]
Readme comments:

1. First list item, end of the sentence should be "for review and comparison".
2. Requirement list item 3 already mentioned in initial list point 2. I suggest you delete the requirement list item 3. (You also mention it in the rsa notebook too).
3. Grammatical error in last sentence, I suggest:  We appreciate the efforts of each of these projects that helped us in our own research. 

When downloading zip file, the zipfiles name is doublehardmulticlass-readme-update .. can we change that so that when it downloads its just doublehardmulticlass?

**Pull request merged**
